### ISSUE TITLE
ERR_NON_2XX_3XX_RESPONSE

### ISSUE THREAD

**Issue by LordJBrown** [ak--47/mixpanel-import#10]
Hi AK,

Thank you for all the wonderful work you provide to the community.

I've been running the following command for the last few months and now, unexpectedly I received an code: 'ERR_NON_2XX_3XX_RESPONSE',

npx --yes mixpanel-import --type export --start 2024-04-05 --end 2024-05-05 --secret <sourceKey>   && npx --yes mixpanel-import --offset -1 --recordsPerBatch 500 .\mixpanel-exports\ --secret <deskKey>

Please advise.
Er

C:\Users\AppData\Local\npm-cache\_npx\d93516675bc9874c\node_modules\mixpanel-import\components\exporters.js:71
                throw e;
                ^

HTTPError: Response code 500 (Internal Server Error)
    at Request._onResponseBase (C:\Users\AppData\Local\npm-cache\_npx\d93516675bc9874c\node_modules\got\dist\source\core\index.js:913:31)
    at Request._onResponse (C:\Users\AppData\Local\npm-cache\_npx\d93516675bc9874c\node_modules\got\dist\source\core\index.js:948:24)
    at ClientRequest.<anonymous> (C:\Users\AppData\Local\npm-cache\_npx\d93516675bc9874c\node_modules\got\dist\source\core\index.js:962:23)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at origin.emit (C:\Users\AppData\Local\npm-cache\_npx\d93516675bc9874c\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:535:22)
    at TLSSocket.emit (node:events:514:28) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1715502068899,
    socket: 1715502068902,
    lookup: 1715502068976,
    connect: 1715502068982,
    secureConnect: 1715502068997,
    upload: 1715502068997,
    response: 1715502806532,
    end: 1715502806534,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 74,
      tcp: 6,
      tls: 15,
      request: 0,
      firstByte: 737535,
      download: 2,
      total: 737635
    }
  }
}

Node.js v20.10.0

**Comment by LordJBrown** [comment]
Found the issue in the my script
